@baseUrl = http://sigashomologa.prodemge.gov.br/sigas-web/rest
@token = cc88d226-cfc8-4fc9-9b61-b45c69c322f5
###
// 5 - com dados
// 5 /autorizacao/confirma-procedimento
GET {{baseUrl}}/autorizacao/confirma-procedimento
?senha=KXV5000
&cpfExecutante=05175053678
&cbos=225260
Content-Type: application/json
Authentication: {{token}}

###
// 5 - sem dados
// 5 /autorizacao/confirma-procedimento
GET {{baseUrl}}/autorizacao/confirma-procedimento
?senha=KGYBPB0
&cpfExecutante=
&cbos=
Content-Type: application/json
Authentication: {{token}}

###