@baseUrl = http://sigashomologa.prodemge.gov.br/sigas-web/rest
@token = f45bb538-82e5-4486-b4ce-d12d44a2e1d3
###
// 4 - FARMÁCIA
// 4.1 /farmacia/solicita-medicamento
POST {{baseUrl}}/farmacia/solicita-medicamento
Content-Type: application/json
Authentication: {{token}}

< ./endpoint/farmacia/solicita-medicamento/body.json
###