@baseUrl = http://sigashomologa.prodemge.gov.br/sigas-web/rest
@token = 6b86e9ad-d3c6-4c76-ba03-8913e2bb0e91
###
// 2 - ELEGIBILIDADE
// 2.1 /elegibilidade/verifica-elegibilidade
POST {{baseUrl}}/elegibilidade/verifica-elegibilidade
Content-Type: application/json
Authentication: {{token}}

< ./body/elegibilidade/verifica-elegibilidade/body.json
###
// 3.0 Assistencia a saúde
// 3.1 /autorizacao/solicita-procedimento
POST {{baseUrl}}/autorizacao/solicita-procedimento
Content-Type: application/json
Authentication: {{token}}

< ./body/autorizacao/solicita-procedimento/body.json
###
// 3.0 Assistencia a saúde
// 3.2 /autorizacao/status-autorizacao
POST {{baseUrl}}/autorizacao/status-autorizacao
Content-Type: application/json
Authentication: {{token}}

< ./body/autorizacao/status-autorizacao/body.json
###
// 3.0 Assistencia a saúde
// 3.3 /autorizacao/cancela-procedimento
POST {{baseUrl}}/autorizacao/cancela-procedimento
Content-Type: application/json
Authentication: {{token}}

< ./body/autorizacao/cancela-procedimento/body.json
###
// 4 - FARMÁCIA
// 4.1 /farmacia/solicita-medicamento
POST {{baseUrl}}/farmacia/solicita-medicamento
Content-Type: application/json
Authentication: {{token}}

< ./body/farmacia/solicita-medicamento/body.json
###
// 4 - FARMÁCIA
// 4.2 /farmacia/cancela-medicamento
POST {{baseUrl}}/farmacia/cancela-medicamento
Content-Type: application/json
Authentication: {{token}}

< ./body/farmacia/cancela-medicamento/body.json
###
